create table if not exists public.products (
  id bigint primary key,
  name text not null,
  brand text not null,
  category text not null,
  type text not null,
  barcode text not null default '',
  description text not null default '',
  stock integer not null default 0,
  tone text not null default '',
  price numeric null,
  image_url text not null default '',
  image_urls jsonb not null default '[]'::jsonb,
  reference_url text not null default '',
  is_active boolean not null default true,
  image_key text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.products
add column if not exists is_active boolean not null default true;

alter table public.products
add column if not exists barcode text not null default '';

alter table public.products
add column if not exists image_urls jsonb not null default '[]'::jsonb;

create or replace function public.set_products_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists products_set_updated_at on public.products;

create trigger products_set_updated_at
before update on public.products
for each row
execute function public.set_products_updated_at();

alter table public.products enable row level security;
grant usage on schema public to anon, authenticated;
revoke select on public.products from anon;
grant select on public.products to authenticated;
grant insert, update, delete on public.products to authenticated;

drop policy if exists "products_public_read" on public.products;
drop policy if exists "products_authenticated_read" on public.products;
create policy "products_authenticated_read"
on public.products
for select
to authenticated
using (true);

drop policy if exists "products_public_write" on public.products;
drop policy if exists "products_authenticated_write" on public.products;
create policy "products_authenticated_write"
on public.products
for all
to authenticated
using (true)
with check (true);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  total numeric not null default 0,
  item_count integer not null default 0,
  whatsapp_message text not null default '',
  status text not null default 'nuevo',
  created_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id bigint null,
  product_name text not null default '',
  brand text not null default '',
  category text not null default '',
  tone text not null default '',
  quantity integer not null default 1,
  unit_price numeric null,
  created_at timestamptz not null default now()
);

alter table public.orders enable row level security;
alter table public.order_items enable row level security;
grant insert on public.orders to anon, authenticated;
grant select, update, delete on public.orders to authenticated;
grant insert on public.order_items to anon, authenticated;
grant select on public.order_items to authenticated;
grant usage, select on sequence public.orders_id_seq to anon, authenticated;
grant usage, select on sequence public.order_items_id_seq to anon, authenticated;

drop policy if exists "orders_public_insert" on public.orders;
create policy "orders_public_insert"
on public.orders
for insert
to anon, authenticated
with check (true);

drop policy if exists "orders_admin_select" on public.orders;
create policy "orders_admin_select"
on public.orders
for select
to authenticated
using (true);

drop policy if exists "orders_admin_update" on public.orders;
create policy "orders_admin_update"
on public.orders
for update
to authenticated
using (true)
with check (true);

drop policy if exists "orders_admin_delete" on public.orders;
create policy "orders_admin_delete"
on public.orders
for delete
to authenticated
using (true);

drop policy if exists "order_items_public_insert" on public.order_items;
create policy "order_items_public_insert"
on public.order_items
for insert
to anon, authenticated
with check (true);

drop policy if exists "order_items_admin_select" on public.order_items;
create policy "order_items_admin_select"
on public.order_items
for select
to authenticated
using (true);
